# Generated by Django 5.0.1 on 2024-01-31 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5, unique=True)),
                ('category', models.CharField(choices=[('SGL', 'Single'), ('DBL', 'Double'), ('TPL', 'Triple'), ('LX', 'Luxury')], max_length=7)),
                ('beds', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='room_images', verbose_name='Image')),
            ],
        ),
    ]
