# Generated by Django 5.0.1 on 2024-03-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
