# Generated by Django 5.0.1 on 2024-02-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('Single', 'SGL'), ('Double', 'DBL'), ('Family', 'FM'), ('Luxury', 'LX')], max_length=7),
        ),
    ]
