# Generated by Django 5.1.3 on 2025-05-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0002_user_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирования'},
        ),
        migrations.AlterModelOptions(
            name='commission',
            options={'verbose_name': 'Коммиссию', 'verbose_name_plural': 'Коммиссии'},
        ),
        migrations.AlterModelOptions(
            name='mealplan',
            options={'verbose_name': 'План питания', 'verbose_name_plural': 'Планы питания'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Клиенты', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Оплату', 'verbose_name_plural': 'Оплаты'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Номер', 'verbose_name_plural': 'Номера'},
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='type',
            field=models.CharField(choices=[('standard', 'Стандартное питание'), ('breakfast', 'Завтрак'), ('all_inclusive', 'Всё включено')], max_length=20, unique=True),
        ),
        migrations.AlterModelTable(
            name='booking',
            table='booking_app_booking',
        ),
        migrations.AlterModelTable(
            name='commission',
            table='booking_app_commission',
        ),
        migrations.AlterModelTable(
            name='mealplan',
            table='booking_app_mealplan',
        ),
        migrations.AlterModelTable(
            name='partner',
            table='booking_app_partner',
        ),
        migrations.AlterModelTable(
            name='payment',
            table='booking_app_payment',
        ),
        migrations.AlterModelTable(
            name='review',
            table='booking_app_review',
        ),
        migrations.AlterModelTable(
            name='room',
            table='booking_app_room',
        ),
    ]
