# Generated by Django 5.0.1 on 2024-02-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0002_alter_room_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('single', 'SGL'), ('double', 'DBL'), ('family', 'FM'), ('luxury', 'LX')], max_length=7),
        ),
    ]
