# Generated by Django 5.0.1 on 2024-02-01 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0003_booking_payment_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='user_id',
            new_name='id_user',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='room_id',
        ),
        migrations.AlterField(
            model_name='booking',
            name='room_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_app.room', to_field='number'),
        ),
    ]
